### ISSUE TITLE
Java Program to Check Whether a Number is Even or Odd

### ISSUE THREAD

**Issue by sujana-kamasany** [sujana-kamasany/javacodes#7]
Add Java Program to Check Whether a Number is Even or Odd

**Comment by AKhatabdev** [comment]
Hello,

I would like to work on this issue. 

Kind regards

**Comment by sujana-kamasany** [comment]
> Hello,
> 
> I'll work on this issue and submit a PR soon.
> 
> Kind regards

@AKhatabdev Yes you can!

**Comment by AKhatabdev** [comment]
@sujana-kamasany close Issue 👍 

Kind regards
